# ─────Background──────────────────────────────────────────────────────────────

background {
    color = rgb(0, 0, 0)
    path = $HOME/wallpapers/lock_screen/current
}

# ─────Battery─────────────────────────────────────────────────────────────────

label {
    color = rgb(200, 200, 200)
    font_size = 10
    halign = right
    position = -10, -10
    text = cmd[update:1000] upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep percentage | awk '{print $2}'
    valign = top
}

# ─────Keyboard Layout─────────────────────────────────────────────────────────

label {
    color = rgb(200, 200, 200)
    font_size = 10
    halign = right
    position = -10, -30
    text = $LAYOUT
    valign = top
}

# ─────Date────────────────────────────────────────────────────────────────────

label {
    color = rgb(200, 200, 200)
    font_size = 20
    halign = left
    position = 90, -220
    text = cmd[update:1000] echo "$(date +'%A, %d %B')"
    valign = top
}

# ─────Hours───────────────────────────────────────────────────────────────────

label {
    color = rgb(200, 200, 200)
    font_size = 130
    halign = left
    position = 30, -20
    text = cmd[update:1000] echo "$(date +%H)"
    valign = top
}

# ─────Minutes─────────────────────────────────────────────────────────────────

label {
    color = rgb(200, 200, 200)
    font_size = 70
    halign = left
    position = 250, -95
    text = cmd[update:1000] echo "$(date +%M)"
    valign = top
}

# ─────Password─Input──────────────────────────────────────────────────────────

input-field {
    halign = right
    position = -30, 30
    valign = bottom

    check_color = rgb(15, 15, 15)
    dots_center = true
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    dots_size = 0.3
    dots_spacing = 0.2
    fade_on_empty = true
    fade_timeout = 0 # milliseconds before fade_on_empty is triggered
    fail_color = rgb(15, 15, 15)
    fail_text =
    fail_timeout = 0 # milliseconds before fail_text and fail_color disappears
    fail_transition = 0 # transition time in ms between normal outer_color and fail_color
    hide_input = false
    outline_thickness = 3
    placeholder_text =
    rounding = 10
    size = 200, 50
    swap_font_color = false

    bothlock_color = -1 # capslock and numlock
    capslock_color = -1
    invert_numlock = false # change color if numlock is off
    numlock_color = -1

    # Dark theme
    font_color = rgb(200, 200, 200)
    inner_color = rgb(30, 30, 30)
    outer_color = rgb(20, 20, 20)

    # Light theme
    # font_color = rgb(10, 10, 10)
    # inner_color = rgb(200, 200, 200)
    # outer_color = rgb(15, 15, 15)
}

# ─────Useful─Links────────────────────────────────────────────────────────────

# https://github.com/hyprwm/Hyprland
# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock

# ─────Other─Configurations────────────────────────────────────────────────────

# https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/hypr/hyprlock.conf
