[window]
padding = { x = 20, y = 20 }
decorations = "None"
opacity = 0.9

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[font]
size = 19

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

